FROM postgres:latest

# Install necessary packages to interact with HashiCorp Vault


RUN apt-get update && apt-get install -y \
    jq \
    curl \
 && rm -rf /var/lib/apt/lists/*

# Copy initialization script into the container
COPY db/01-init.sh /docker-entrypoint-initdb.d/01-init.sh

# Set permissions for the initialization script
RUN chmod +x /docker-entrypoint-initdb.d/01-init.sh

